#!/bin/bash
set -e

(cd ../commons && atlas-mvn package install -DskipTests)

atlas-package -DskipTests

ports=$(docker ps --format "{{.Names}}: {{.Ports}}" | rg '(.*_confluence_.*:)([0-9]+)(->.*)' --replace '$2')

for port in $ports ; do
	atlas-install-plugin -o --context-path '' -p $port
done