#!/bin/bash
set -e

(cd ../commons && atlas-mvn package install -DskipTests)

atlas-package -DskipTests

ips=$(docker ps --quiet | xargs --no-run-if-empty docker inspect --format='{{.Name}}|{{range $net, $conf := .NetworkSettings.Networks}}{{$conf.IPAddress}} {{end}}' | rg '(.*_jira_.*\|)(.*)' --replace '$2')

for ip in $ips ; do
	atlas-install-plugin -o --context-path '' -p 8080 --server $ip
done
